namespace: ipinfusion
name: ocnos
version: 1.2.5
readme: README.md
authors:
  - Sharath Samanth <sharath.samanth@ipinfusion.com>
description: Collection Containing OcNOS Modules for config backup, software update etc..
license: GPL-3.0-or-later
tags: [networking, backup, plugin]

